FROM python:3.10
USER root

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
RUN apt-get install -y vim less git postgresql-client

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

ARG DJANGO_SECRET_KEY=DJANGO_SECRET_KEY
ARG AES_KEY=AES_KEY
ARG EMAIL_HOST=EMAIL_HOST
ARG EMAIL_PORT=EMAIL_PORT
ARG EMAIL_HOST_USER=EMAIL_HOST_USER
ARG EMAIL_HOST_PASSWORD=EMAIL_HOST_PASSWORD
ARG SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
ARG SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
ARG POSTGRES_DB=POSTGRES_DB
ARG POSTGRES_USER=POSTGRES_USER
ARG POSTGRES_PASSWORD=POSTGRES_PASSWORD
ARG POSTGRES_HOST=POSTGRES_HOST
ARG POSTGRES_PORT=POSTGRES_PORT

ENV DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
ENV AES_KEY=$AES_KEY
ENV EMAIL_HOST=$EMAIL_HOST
ENV EMAIL_PORT=$EMAIL_PORT
ENV EMAIL_HOST_USER=$EMAIL_HOST_USER
ENV EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
ENV SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=$SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
ENV SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=$SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_PORT=$POSTGRES_PORT

RUN mkdir -p /var/www/omcen
COPY . /var/www/omcen

WORKDIR /var/www/omcen

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install -r ./requirements/product.txt

RUN python config/public_key.py

RUN python manage.py collectstatic --noinput
RUN python manage.py makemigrations accounts
RUN python manage.py makemigrations omcen
RUN python manage.py makemigrations password_box
RUN python manage.py makemigrations file_encryption
RUN python manage.py makemigrations tango